# TODO: To use this template copy and rename this file.
# TODO: See model_chains > example_model_chain_config.yml for reference.
config:
  sys_config: "config/system_config.yml"

models:
  # TODO: Add each model, in order of execution. See example
  model_1:
    # TODO: Add path of model config file starting from repo root directory.
    config: ""
    # TODO: Add path of model wrapper starting from src directory.
    model_path: ""
    # TODO: Add name of model wrapper class contained within the file above.
    model: ""

  model_2:
    # TODO: Add path of model config file starting from repo root directory.
    config: ""
    # TODO: Add path of model wrapper starting from src directory.
    model_path: ""
    # TODO: Add name of model wrapper class contained within the file above.
    model: ""

