# TODO: To use this template copy and rename this file.
# TODO: See example_model > example_model_reconciliation_config.yml for reference.
config:
  log_location: "model_logs/example_model_logs"
  log_name: "example_model_reconciliation_{data}_{date}"
  numeric_threshold: 0.00001
  usecols: False,
  matching_columns: False
  remove_columns: []
  verbose: True

dataset_1:
  schema_path: "src/models/model_schemas/example_model/ecl_data_schema.json"
  main_data_path: "example_model/outputs/ecl_data.csv"
  test_data_path: "example_model/outputs/ecl_data_test.csv"

dataset_2:
  schema_path: "src/models/model_schemas/example_model/ecl_data_schema.json"
  main_data_path: "example_model/outputs/ecl_data.csv"
  test_data_path: "example_model/outputs/ecl_data_test.csv"
