parameters:

  model_parameters:
    model_id: "example-model"
    model_type: "ifrs9"
    type: "pandas"

model_data:

  inputs:
    pd_data: "example_model/inputs/pd_data.csv"
    lgd_data : "example_model/inputs/lgd_data.csv"
    ead_data: "example_model/inputs/ead_data.csv"
    parameters: "parameters.csv"

  outputs:
    ecl_data: "example_model/outputs/ecl_data.csv"
