parameters:

  model_parameters:
    model_id: "example-model"
    model_type: "ifrs9"
    type: "pandas"

model_data:

  inputs:
    pd_data: ""
    lgd_data : ""
    ead_data: ""

  outputs:
    ecl_data: ""
