parameters:
  model_id: "example-model"
  model_type: "pandas"
  type: "pandas"
  log: "model_logs/example_model_logs/example_model_log_{date}.log"

  model_parameters:
    ecl_upper_limit: 500
    ecl_lower_limit: 200

model_data:

  inputs:
    pd_data: "example_model/inputs/pd_data.csv"
    lgd_data: "example_model/inputs/lgd_data.csv"
    ead_data: "example_model/inputs/ead_data.csv"

  outputs:
    ecl_data: "example_model/outputs/ecl_data.csv"
