config:
  sys_config: "config/system_config.yml"
  model_config: "config/model_config/example_model/example_model_config.yml"
  model_wrapper: "src.models.model_wrappers.example_model_wrapper"
  model_wrapper_class: "ExampleModelWrapper"